name = "Escape"
default_targets = ["win32", "win64", "appimage"]
build_directory = "makelove-build"

love_files = [
    "./source/*.lua",
    "./source/lib/*",
    "./source/assets/*",
    "./main.lua"
]

[hooks]
prebuild = [
	"./run.py -s -l"
]

postbuild = [
    "./run.py -l"
]
