name = "Escape"
default_targets = ["win32", "win64", "appimage"]
build_directory = "makelove-build"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]

[hooks]

prebuild = [
	"./run.py -s -l"
]

postbuild = [
    "./run.py -l"
]
